### ISSUE TITLE
When internal server stops for ~1 minute, Grappl stops responding

### ISSUE THREAD

**Issue by the-blaster179** [Cactose/Grappl#10]
<h3>What happened?

I was hosting a Minecraft server with the internal port being 25565 on the p.grappl.io server when I had to stop the server to do some configuring. About 2 minutes later, I started the server up, but Grappl wouldn't send the server packets out anymore, making it sort of stop responding. You could still open console, use the console commands, etc. but it just wouldn't send the packets out no matter what I did other than restarting Grappl itself.

<h3>What should have happened?

The Grappl should have resumed sending the packets.

<h3>Environment

Ubuntu Linux 14.04 LTS
Java 8 Latest

**Comment by Cactose** [comment]
I think this happens when someone attempts to connect to the internal server through Grappl while it's down, producing an exception internally and breaking everything.

Is it possible that is what happened in your case?

**Comment by the-blaster179** [comment]
Possibly, however this has been fixed in the latest version of Grappl as far as I can tell. I forgot to close this issue.
