### ISSUE TITLE
Install folder is null

### ISSUE THREAD

**Issue by 0xTJ** [Cactose/Grappl#3]
![capture](https://cloud.githubusercontent.com/assets/7854414/8397963/0cf68cb0-1dac-11e5-8407-780e4a78b285.JPG)
 After running the latest updater jar, in this Debian system, the istall path is the home and an extra null.

**Comment by 0xTJ** [comment]
It would seem, after some more testing, that in AutoUpdater.java
`<114>` return System.getenv("user.home") + "/";
returns only "null/" resulting in the problem. When the updater is moved to another directory, it is then that_directory/null.

**Comment by Cactose** [comment]
Huh, must be the wrong environmental variable. Thanks for pointing this out, I've glanced at the code a few times and wasn't sure what was causing this issue.

**Comment by Cactose** [comment]
Now fixed in the repository, although changes are not in the released launchers yet
