### ISSUE TITLE
Can't log into the client 

### ISSUE THREAD

**Issue by empirebuilder1** [Cactose/Grappl#7]
I created an account on grappl.io, then attempted to log into the account on the grappl client. The client freezes and refuses to close without killing the process. Occurs in both Windows 8.1 (exe launcher) and Ubuntu Linux 14.04 (standalone jar).

**Comment by 0xTJ** [comment]
Could not reproduce issue using newest client with a previously-existing account.

**Comment by empirebuilder1** [comment]
Appears to be a problem with the particular account I was using. Created a new account, was able to log in fine. Closing as it is not an actual problem with the program.
